# Generated by Django 2.1.15 on 2021-04-22 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('patronymic', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('telephone', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Nominant',
        ),
    ]
