# Generated by Django 2.1.15 on 2021-04-23 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbapi', '0002_auto_20210422_1822'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nominant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='ContactModel',
        ),
    ]
