# Generated by Django 2.1.15 on 2021-04-25 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbapi', '0003_auto_20210423_0912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nominant',
            name='name',
        ),
    ]
