# Generated by Django 2.1.15 on 2021-04-25 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbapi', '0004_remove_nominant_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nominant',
            name='age',
        ),
        migrations.AddField(
            model_name='nominant',
            name='name',
            field=models.CharField(default='test', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nominant',
            name='surname',
            field=models.CharField(default='default_surname', max_length=30),
            preserve_default=False,
        ),
    ]
