# Generated by Django 2.1.15 on 2021-04-27 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbapi', '0005_auto_20210425_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grammy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Nominant',
        ),
    ]
